name: Build and push Docker image

on:
  push:
    branches: [main]

jobs:
  # Job 1: Build and push the application image
  build-and-push-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.app
          push: true
          tags: sonrichs/content-products-api:latest
          build-args: |
            CONTENTFUL_BASE_URL=${{ vars.CONTENTFUL_BASE_URL }}
            CONTENTFUL_ENTRIES_PATH=${{ vars.CONTENTFUL_ENTRIES_PATH }}
            CONTENTFUL_SPACE_ID=${{ vars.CONTENTFUL_SPACE_ID }}
            CONTENTFUL_ENVIRONMENT=${{ vars.CONTENTFUL_ENVIRONMENT }}
            CONTENTFUL_CONTENT_TYPE=${{ vars.CONTENTFUL_CONTENT_TYPE }}
            MOCKI_API_URL=${{ vars.MOCKI_API_URL }}
            DB_HOST=${{ vars.DB_HOST }}
            DB_PORT=${{ vars.DB_PORT }}
            DB_NAME=${{ vars.DB_NAME }}
            PORT=3000
            NODE_ENV=production
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

  # Job 2: Build and push the cp-api PostgreSQL image
  build-and-push-postgresql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image (PostgreSQL)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.pg
          push: true
          tags: sonrichs/cp-api-postgres:latest
          build-args: |
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ vars.DB_NAME }}
